// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import "strconv"

type NodeFlag uint32

const (
	NodeFlagNone         NodeFlag = 0
	NodeFlagNodeIndexed  NodeFlag = 1
	NodeFlagNodeBinary   NodeFlag = 2
	NodeFlagNodeUnary    NodeFlag = 4
	NodeFlagPlaceHolder1 NodeFlag = 8
	NodeFlagPlaceHolder2 NodeFlag = 16
	NodeFlagPlaceHolder4 NodeFlag = 32
	NodeFlagPlaceHolder5 NodeFlag = 64
	NodeFlagPlaceHolder6 NodeFlag = 128
)

var EnumNamesNodeFlag = map[NodeFlag]string{
	NodeFlagNone:         "None",
	NodeFlagNodeIndexed:  "NodeIndexed",
	NodeFlagNodeBinary:   "NodeBinary",
	NodeFlagNodeUnary:    "NodeUnary",
	NodeFlagPlaceHolder1: "PlaceHolder1",
	NodeFlagPlaceHolder2: "PlaceHolder2",
	NodeFlagPlaceHolder4: "PlaceHolder4",
	NodeFlagPlaceHolder5: "PlaceHolder5",
	NodeFlagPlaceHolder6: "PlaceHolder6",
}

var EnumValuesNodeFlag = map[string]NodeFlag{
	"None":         NodeFlagNone,
	"NodeIndexed":  NodeFlagNodeIndexed,
	"NodeBinary":   NodeFlagNodeBinary,
	"NodeUnary":    NodeFlagNodeUnary,
	"PlaceHolder1": NodeFlagPlaceHolder1,
	"PlaceHolder2": NodeFlagPlaceHolder2,
	"PlaceHolder4": NodeFlagPlaceHolder4,
	"PlaceHolder5": NodeFlagPlaceHolder5,
	"PlaceHolder6": NodeFlagPlaceHolder6,
}

func (v NodeFlag) String() string {
	if s, ok := EnumNamesNodeFlag[v]; ok {
		return s
	}
	return "NodeFlag(" + strconv.FormatInt(int64(v), 10) + ")"
}
