// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import "strconv"

type Opcode uint32

const (
	OpcodePackage          Opcode = 0
	OpcodeImport           Opcode = 1
	OpcodeImportValue      Opcode = 2
	OpcodeConst            Opcode = 3
	OpcodeConstValue       Opcode = 4
	OpcodeVar              Opcode = 5
	OpcodeVarValue         Opcode = 6
	OpcodeType             Opcode = 7
	OpcodeFunc             Opcode = 8
	OpcodeIf               Opcode = 9
	OpcodeFor              Opcode = 10
	OpcodeForRange         Opcode = 11
	OpcodeSwitch           Opcode = 12
	OpcodeSelect           Opcode = 13
	OpcodeCase             Opcode = 14
	OpcodeDefault          Opcode = 15
	OpcodeAdd              Opcode = 16
	OpcodeSub              Opcode = 17
	OpcodeMul              Opcode = 18
	OpcodeDiv              Opcode = 19
	OpcodeMod              Opcode = 20
	OpcodeInc              Opcode = 21
	OpcodeDec              Opcode = 22
	OpcodeAssign           Opcode = 23
	OpcodeAddAssign        Opcode = 24
	OpcodeSubAssign        Opcode = 25
	OpcodeMulAssign        Opcode = 26
	OpcodeDivAssign        Opcode = 27
	OpcodeModAssign        Opcode = 28
	OpcodeBitAndAssign     Opcode = 29
	OpcodeBitOrAssign      Opcode = 30
	OpcodeBitXorAssign     Opcode = 31
	OpcodeBitClearAssign   Opcode = 32
	OpcodeLeftShiftAssign  Opcode = 33
	OpcodeRightShiftAssign Opcode = 34
	OpcodeEqual            Opcode = 35
	OpcodeNotEqual         Opcode = 36
	OpcodeLess             Opcode = 37
	OpcodeLessEqual        Opcode = 38
	OpcodeGreater          Opcode = 39
	OpcodeGreaterEqual     Opcode = 40
	OpcodeAnd              Opcode = 41
	OpcodeOr               Opcode = 42
	OpcodeNot              Opcode = 43
	OpcodeBitAnd           Opcode = 44
	OpcodeBitOr            Opcode = 45
	OpcodeBitXor           Opcode = 46
	OpcodeBitClear         Opcode = 47
	OpcodeLeftShift        Opcode = 48
	OpcodeRightShift       Opcode = 49
	OpcodeSend             Opcode = 50
	OpcodeReceive          Opcode = 51
	OpcodeAddrOf           Opcode = 52
	OpcodeDeref            Opcode = 53
	OpcodeCall             Opcode = 54
	OpcodeReturn           Opcode = 55
	OpcodeDefer            Opcode = 56
	OpcodeGoRoutine        Opcode = 57
	OpcodeMap              Opcode = 58
	OpcodeArray            Opcode = 59
	OpcodeChan             Opcode = 60
	OpcodePanic            Opcode = 61
	OpcodeRecover          Opcode = 62
	OpcodeMake             Opcode = 63
	OpcodeNew              Opcode = 64
	OpcodeLen              Opcode = 65
	OpcodeCap              Opcode = 66
	OpcodeAppend           Opcode = 67
	OpcodeCopy             Opcode = 68
	OpcodeClose            Opcode = 69
	OpcodeComplex          Opcode = 70
	OpcodeReal             Opcode = 71
	OpcodeImag             Opcode = 72
	OpcodePrint            Opcode = 73
	OpcodePrintln          Opcode = 74
)

var EnumNamesOpcode = map[Opcode]string{
	OpcodePackage:          "Package",
	OpcodeImport:           "Import",
	OpcodeImportValue:      "ImportValue",
	OpcodeConst:            "Const",
	OpcodeConstValue:       "ConstValue",
	OpcodeVar:              "Var",
	OpcodeVarValue:         "VarValue",
	OpcodeType:             "Type",
	OpcodeFunc:             "Func",
	OpcodeIf:               "If",
	OpcodeFor:              "For",
	OpcodeForRange:         "ForRange",
	OpcodeSwitch:           "Switch",
	OpcodeSelect:           "Select",
	OpcodeCase:             "Case",
	OpcodeDefault:          "Default",
	OpcodeAdd:              "Add",
	OpcodeSub:              "Sub",
	OpcodeMul:              "Mul",
	OpcodeDiv:              "Div",
	OpcodeMod:              "Mod",
	OpcodeInc:              "Inc",
	OpcodeDec:              "Dec",
	OpcodeAssign:           "Assign",
	OpcodeAddAssign:        "AddAssign",
	OpcodeSubAssign:        "SubAssign",
	OpcodeMulAssign:        "MulAssign",
	OpcodeDivAssign:        "DivAssign",
	OpcodeModAssign:        "ModAssign",
	OpcodeBitAndAssign:     "BitAndAssign",
	OpcodeBitOrAssign:      "BitOrAssign",
	OpcodeBitXorAssign:     "BitXorAssign",
	OpcodeBitClearAssign:   "BitClearAssign",
	OpcodeLeftShiftAssign:  "LeftShiftAssign",
	OpcodeRightShiftAssign: "RightShiftAssign",
	OpcodeEqual:            "Equal",
	OpcodeNotEqual:         "NotEqual",
	OpcodeLess:             "Less",
	OpcodeLessEqual:        "LessEqual",
	OpcodeGreater:          "Greater",
	OpcodeGreaterEqual:     "GreaterEqual",
	OpcodeAnd:              "And",
	OpcodeOr:               "Or",
	OpcodeNot:              "Not",
	OpcodeBitAnd:           "BitAnd",
	OpcodeBitOr:            "BitOr",
	OpcodeBitXor:           "BitXor",
	OpcodeBitClear:         "BitClear",
	OpcodeLeftShift:        "LeftShift",
	OpcodeRightShift:       "RightShift",
	OpcodeSend:             "Send",
	OpcodeReceive:          "Receive",
	OpcodeAddrOf:           "AddrOf",
	OpcodeDeref:            "Deref",
	OpcodeCall:             "Call",
	OpcodeReturn:           "Return",
	OpcodeDefer:            "Defer",
	OpcodeGoRoutine:        "GoRoutine",
	OpcodeMap:              "Map",
	OpcodeArray:            "Array",
	OpcodeChan:             "Chan",
	OpcodePanic:            "Panic",
	OpcodeRecover:          "Recover",
	OpcodeMake:             "Make",
	OpcodeNew:              "New",
	OpcodeLen:              "Len",
	OpcodeCap:              "Cap",
	OpcodeAppend:           "Append",
	OpcodeCopy:             "Copy",
	OpcodeClose:            "Close",
	OpcodeComplex:          "Complex",
	OpcodeReal:             "Real",
	OpcodeImag:             "Imag",
	OpcodePrint:            "Print",
	OpcodePrintln:          "Println",
}

var EnumValuesOpcode = map[string]Opcode{
	"Package":          OpcodePackage,
	"Import":           OpcodeImport,
	"ImportValue":      OpcodeImportValue,
	"Const":            OpcodeConst,
	"ConstValue":       OpcodeConstValue,
	"Var":              OpcodeVar,
	"VarValue":         OpcodeVarValue,
	"Type":             OpcodeType,
	"Func":             OpcodeFunc,
	"If":               OpcodeIf,
	"For":              OpcodeFor,
	"ForRange":         OpcodeForRange,
	"Switch":           OpcodeSwitch,
	"Select":           OpcodeSelect,
	"Case":             OpcodeCase,
	"Default":          OpcodeDefault,
	"Add":              OpcodeAdd,
	"Sub":              OpcodeSub,
	"Mul":              OpcodeMul,
	"Div":              OpcodeDiv,
	"Mod":              OpcodeMod,
	"Inc":              OpcodeInc,
	"Dec":              OpcodeDec,
	"Assign":           OpcodeAssign,
	"AddAssign":        OpcodeAddAssign,
	"SubAssign":        OpcodeSubAssign,
	"MulAssign":        OpcodeMulAssign,
	"DivAssign":        OpcodeDivAssign,
	"ModAssign":        OpcodeModAssign,
	"BitAndAssign":     OpcodeBitAndAssign,
	"BitOrAssign":      OpcodeBitOrAssign,
	"BitXorAssign":     OpcodeBitXorAssign,
	"BitClearAssign":   OpcodeBitClearAssign,
	"LeftShiftAssign":  OpcodeLeftShiftAssign,
	"RightShiftAssign": OpcodeRightShiftAssign,
	"Equal":            OpcodeEqual,
	"NotEqual":         OpcodeNotEqual,
	"Less":             OpcodeLess,
	"LessEqual":        OpcodeLessEqual,
	"Greater":          OpcodeGreater,
	"GreaterEqual":     OpcodeGreaterEqual,
	"And":              OpcodeAnd,
	"Or":               OpcodeOr,
	"Not":              OpcodeNot,
	"BitAnd":           OpcodeBitAnd,
	"BitOr":            OpcodeBitOr,
	"BitXor":           OpcodeBitXor,
	"BitClear":         OpcodeBitClear,
	"LeftShift":        OpcodeLeftShift,
	"RightShift":       OpcodeRightShift,
	"Send":             OpcodeSend,
	"Receive":          OpcodeReceive,
	"AddrOf":           OpcodeAddrOf,
	"Deref":            OpcodeDeref,
	"Call":             OpcodeCall,
	"Return":           OpcodeReturn,
	"Defer":            OpcodeDefer,
	"GoRoutine":        OpcodeGoRoutine,
	"Map":              OpcodeMap,
	"Array":            OpcodeArray,
	"Chan":             OpcodeChan,
	"Panic":            OpcodePanic,
	"Recover":          OpcodeRecover,
	"Make":             OpcodeMake,
	"New":              OpcodeNew,
	"Len":              OpcodeLen,
	"Cap":              OpcodeCap,
	"Append":           OpcodeAppend,
	"Copy":             OpcodeCopy,
	"Close":            OpcodeClose,
	"Complex":          OpcodeComplex,
	"Real":             OpcodeReal,
	"Imag":             OpcodeImag,
	"Print":            OpcodePrint,
	"Println":          OpcodePrintln,
}

func (v Opcode) String() string {
	if s, ok := EnumNamesOpcode[v]; ok {
		return s
	}
	return "Opcode(" + strconv.FormatInt(int64(v), 10) + ")"
}
