// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package program

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ArrayType struct {
	_tab flatbuffers.Table
}

func GetRootAsArrayType(buf []byte, offset flatbuffers.UOffsetT) *ArrayType {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ArrayType{}
	x.Init(buf, n+offset)
	return x
}

func FinishArrayTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsArrayType(buf []byte, offset flatbuffers.UOffsetT) *ArrayType {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ArrayType{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedArrayTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ArrayType) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ArrayType) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ArrayType) Elem() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ArrayType) MutateElem(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *ArrayType) Size() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ArrayType) MutateSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func ArrayTypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ArrayTypeAddElem(builder *flatbuffers.Builder, elem uint32) {
	builder.PrependUint32Slot(0, elem, 0)
}
func ArrayTypeAddSize(builder *flatbuffers.Builder, size uint64) {
	builder.PrependUint64Slot(1, size, 0)
}
func ArrayTypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
