// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package program

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChanType struct {
	_tab flatbuffers.Table
}

func GetRootAsChanType(buf []byte, offset flatbuffers.UOffsetT) *ChanType {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChanType{}
	x.Init(buf, n+offset)
	return x
}

func FinishChanTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChanType(buf []byte, offset flatbuffers.UOffsetT) *ChanType {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChanType{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChanTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChanType) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChanType) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChanType) Elem(obj *TypeDef) *TypeDef {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TypeDef)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChanType) Dir() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChanType) MutateDir(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func ChanTypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ChanTypeAddElem(builder *flatbuffers.Builder, elem flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(elem), 0)
}
func ChanTypeAddDir(builder *flatbuffers.Builder, dir uint32) {
	builder.PrependUint32Slot(1, dir, 0)
}
func ChanTypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
