// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package program

import "strconv"

type Flag uint32

const (
	FlagNone        Flag = 0
	FlagNodeIndexed Flag = 1
	FlagNodeBinary  Flag = 2
	FlagNodeUnary   Flag = 4
)

var EnumNamesFlag = map[Flag]string{
	FlagNone:        "None",
	FlagNodeIndexed: "NodeIndexed",
	FlagNodeBinary:  "NodeBinary",
	FlagNodeUnary:   "NodeUnary",
}

var EnumValuesFlag = map[string]Flag{
	"None":        FlagNone,
	"NodeIndexed": FlagNodeIndexed,
	"NodeBinary":  FlagNodeBinary,
	"NodeUnary":   FlagNodeUnary,
}

func (v Flag) String() string {
	if s, ok := EnumNamesFlag[v]; ok {
		return s
	}
	return "Flag(" + strconv.FormatInt(int64(v), 10) + ")"
}
