// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package program

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MapType struct {
	_tab flatbuffers.Table
}

func GetRootAsMapType(buf []byte, offset flatbuffers.UOffsetT) *MapType {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MapType{}
	x.Init(buf, n+offset)
	return x
}

func FinishMapTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMapType(buf []byte, offset flatbuffers.UOffsetT) *MapType {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MapType{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMapTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MapType) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MapType) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MapType) Key() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MapType) MutateKey(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *MapType) Value() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MapType) MutateValue(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func MapTypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MapTypeAddKey(builder *flatbuffers.Builder, key uint32) {
	builder.PrependUint32Slot(0, key, 0)
}
func MapTypeAddValue(builder *flatbuffers.Builder, value uint32) {
	builder.PrependUint32Slot(1, value, 0)
}
func MapTypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
