// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package program

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PointerType struct {
	_tab flatbuffers.Table
}

func GetRootAsPointerType(buf []byte, offset flatbuffers.UOffsetT) *PointerType {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PointerType{}
	x.Init(buf, n+offset)
	return x
}

func FinishPointerTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPointerType(buf []byte, offset flatbuffers.UOffsetT) *PointerType {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PointerType{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPointerTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PointerType) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PointerType) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PointerType) Elem() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PointerType) MutateElem(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func PointerTypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PointerTypeAddElem(builder *flatbuffers.Builder, elem uint32) {
	builder.PrependUint32Slot(0, elem, 0)
}
func PointerTypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
