// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package program

import "strconv"

type ProgramFlag uint32

const (
	ProgramFlagFirstSegment  ProgramFlag = 0
	ProgramFlagSecondSegment ProgramFlag = 1
	ProgramFlagThirdSegment  ProgramFlag = 2
	ProgramFlagForthSegment  ProgramFlag = 4
)

var EnumNamesProgramFlag = map[ProgramFlag]string{
	ProgramFlagFirstSegment:  "FirstSegment",
	ProgramFlagSecondSegment: "SecondSegment",
	ProgramFlagThirdSegment:  "ThirdSegment",
	ProgramFlagForthSegment:  "ForthSegment",
}

var EnumValuesProgramFlag = map[string]ProgramFlag{
	"FirstSegment":  ProgramFlagFirstSegment,
	"SecondSegment": ProgramFlagSecondSegment,
	"ThirdSegment":  ProgramFlagThirdSegment,
	"ForthSegment":  ProgramFlagForthSegment,
}

func (v ProgramFlag) String() string {
	if s, ok := EnumNamesProgramFlag[v]; ok {
		return s
	}
	return "ProgramFlag(" + strconv.FormatInt(int64(v), 10) + ")"
}
