// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package program

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StructureField struct {
	_tab flatbuffers.Table
}

func GetRootAsStructureField(buf []byte, offset flatbuffers.UOffsetT) *StructureField {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StructureField{}
	x.Init(buf, n+offset)
	return x
}

func FinishStructureFieldBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStructureField(buf []byte, offset flatbuffers.UOffsetT) *StructureField {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StructureField{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStructureFieldBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StructureField) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StructureField) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StructureField) Name() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StructureField) MutateName(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *StructureField) Type() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StructureField) MutateType(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *StructureField) Misc() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StructureField) MutateMisc(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func StructureFieldStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func StructureFieldAddName(builder *flatbuffers.Builder, name uint32) {
	builder.PrependUint32Slot(0, name, 0)
}
func StructureFieldAddType(builder *flatbuffers.Builder, type_ uint32) {
	builder.PrependUint32Slot(1, type_, 0)
}
func StructureFieldAddMisc(builder *flatbuffers.Builder, misc uint32) {
	builder.PrependUint32Slot(2, misc, 0)
}
func StructureFieldEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
