// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package program

import "strconv"

type Type byte

const (
	TypeNONE          Type = 0
	TypePointerType   Type = 1
	TypeStructureType Type = 2
	TypeFunctionType  Type = 3
	TypeMapType       Type = 4
	TypeArrayType     Type = 5
	TypeTupleType     Type = 6
)

var EnumNamesType = map[Type]string{
	TypeNONE:          "NONE",
	TypePointerType:   "PointerType",
	TypeStructureType: "StructureType",
	TypeFunctionType:  "FunctionType",
	TypeMapType:       "MapType",
	TypeArrayType:     "ArrayType",
	TypeTupleType:     "TupleType",
}

var EnumValuesType = map[string]Type{
	"NONE":          TypeNONE,
	"PointerType":   TypePointerType,
	"StructureType": TypeStructureType,
	"FunctionType":  TypeFunctionType,
	"MapType":       TypeMapType,
	"ArrayType":     TypeArrayType,
	"TupleType":     TypeTupleType,
}

func (v Type) String() string {
	if s, ok := EnumNamesType[v]; ok {
		return s
	}
	return "Type(" + strconv.FormatInt(int64(v), 10) + ")"
}
